print('\\\\\\--FUNCTIONS--\\\\\\')
print('''
CREATING FUNCTION,
CALLING FUNCTION,
ARGUMENTS,
NUMBER OF ARGUMENTS,
ARBITRARY ARGUMENTS/*ARGS,
KEYWORD ARGUMENTS,
ARBITRARY KEYWORD ARGUMENTS/**KWARGS,
DEFAULT PARAMETER VALUE,
PASSING A LIST AS AN ARGUMENT,
RETURN VALUES,
PASS STATEMENT
''')
